services:
  node_app:
    container_name: node_app
    build: ./api
    image: namarot/node_cs_app
    ports:
      - "3000:3000"
    environment:
      - PG_DB=node_cs_db
      - PG_USER=namarot
      - PG_PASSWORD=12345
      - PG_HOST=node_db
    depends_on:
      - node_db

  node_db:
    container_name: node_db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=node_cs_db
      - POSTGRES_USER=namarot
      - POSTGRES_PASSWORD=12345
    volumes:
      - node_db_data:/var/lib/postgresql/data

volumes:
  node_db_data: {}